name: loono
description: We show prevention matters.
publish_to: "none"
version: 0.1.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  archive: ^3.1.6
  auto_route: ^3.2.2
  built_collection: ^5.1.1
  built_value: ^8.1.3
  cached_network_image: ^3.1.0+1
  collection: ^1.15.0
  crop_your_image: ^0.6.0+1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  device_calendar: ^4.1.0
  device_info_plus: ^3.2.1
  diacritic: ^0.1.3
  dio: ^4.0.0
  email_validator: ^2.0.1
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
      ref: 8f9e2a9edbc6e4fa4d8dfa1dea9c54aec2b38044
  firebase_auth: ^3.1.2
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.7
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.3
  flutter_config: ^2.0.0
  flutter_dotenv: ^5.0.0
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_typeahead: ^3.2.4
  freezed_annotation: ^1.1.0
  geolocator: ^8.1.1
  get_it: ^7.2.0
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.1.0
  google_sign_in: ^5.1.1

  # TODO: Investigate the number of crash occurrences on Xiaomi models https://github.com/flutter/flutter/issues/66322
  #   - possible solution:
  #     - handle MainActivity destruction https://pub.dev/packages/image_picker#handling-mainactivity-destruction-on-android
  image_picker: ^0.8.4+2

  intl: ^0.17.0
  json_annotation: ^4.0.1
  loono_api:
    git:
      url: https://github.com/cesko-digital/loono-api.git
      path: dart
      ref: 5e5616cd489e91e756500b4ab3857b0955abddac
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  moor: ^4.1.0
  onesignal_flutter: ^3.2.4
  package_info_plus: ^1.3.0
  path_provider: ^2.0.2
  permission_handler: ^8.2.5
  provider: ^6.0.1
  sign_in_with_apple: ^3.2.0
  timezone: ^0.8.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  video_player: ^2.1.10

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.0.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  moor_generator: ^4.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/.env
    - assets/icons/
    - assets/icons/prevention/
    - assets/icons/prevention/doctors/
    - assets/intro_video.mp4
    - assets/badges/
    - assets/badges/body/
    - assets/badges/goggles-man/
    - assets/badges/goggles-woman/
    - assets/badges/armour-woman/
    - assets/badges/headband/
    - assets/badges/boots/
    - assets/badges/belt-man/
    - assets/badges/belt-woman/
    - assets/badges/cloak/
    - assets/badges/cloak-buckle/
    - assets/badges/gloves-man/
    - assets/badges/gloves-woman/
    - assets/badges/shield/
