name: loono
description: We show prevention matters.
publish_to: "none"
version: 0.1.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.4.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  dio: ^4.0.0
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
      ref: 8f9e2a9edbc6e4fa4d8dfa1dea9c54aec2b38044
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  moor: ^4.1.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  provider: ^6.0.1
  sqlparser: ^0.17.2
  url_launcher: ^6.0.9 #  TODO: setup on iOS https://pub.dev/packages/url_launcher#ios
  uuid: ^3.0.4
  video_player: ^2.1.10

dev_dependencies:
  auto_route_generator: ^2.4.0
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^5.0.2
  lint: ^1.5.3
  moor_generator: ^4.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/.env
    - assets/icons/
    - assets/intro_video.mp4
