name: loono
description: We show prevention matters.
publish_to: "none"
version: 0.1.3+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.6.3
  another_flushbar: ^1.12.29
  archive: ^3.1.6
  auto_route: ^4.2.1
  badges: ^2.0.1
  built_collection: ^5.1.1
  built_value: ^8.1.3
  cached_network_image: ^3.1.0+1
  collection: ^1.15.0
  connectivity_plus: ^1.4.0
  crop_your_image: ^0.7.2
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  device_calendar: ^4.1.0
  device_info_plus: ^4.0.0
  diacritic: ^0.1.3
  dio: ^4.0.0
  dio_smart_retry: ^1.1.0
  dotted_border: ^2.0.0+2
  drift: ^1.4.0
  easy_debounce: ^2.0.2+1
  email_validator: ^2.0.1
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
      ref: fd0764594dc70b04f5ea5dcd18aa2213abbbce12
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.7
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.1.3
  flutter_config: ^2.0.0
  flutter_dotenv: ^5.0.0
  flutter_inappwebview: ^5.7.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.0.0
  freezed_annotation: ^2.0.3
  geolocator: ^9.0.1
  get_it: ^7.2.0
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.1.0
  google_sign_in: ^5.2.4

  # TODO: Investigate the number of crash occurrences on Xiaomi models https://github.com/flutter/flutter/issues/66322
  #   - possible solution:
  #     - handle MainActivity destruction https://pub.dev/packages/image_picker#handling-mainactivity-destruction-on-android
  image_picker: ^0.8.4+2

  intl: ^0.17.0
  json_annotation: ^4.0.1
  jwt_decoder: ^2.0.1
  loono_api:
    git:
      url: https://github.com/Loono-cz/loono-api.git
      path: dart
      ref: 219d151a97b4169888e8a67d926a23186623ec8e
  modal_progress_hud_nsn: ^0.2.1
  onesignal_flutter: ^3.4.0
  open_store: ^0.2.4
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  provider: ^6.0.1
  share_plus: ^4.0.10
  sign_in_with_apple: ^4.0.0
  sqlite3_flutter_libs: ^0.5.3
  timezone: ^0.8.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  video_player: ^2.1.10
  yaml: ^3.1.0
  youtube_player_flutter: ^8.0.0


dependency_overrides:
  # issue: https://github.com/fluttercommunity/plus_plugins/issues/198
  connectivity_plus: '1.4.0'
  google_sign_in: '5.2.4'
  google_sign_in_platform_interface: '2.1.2'

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.7
  charlatan: ^0.1.0
  drift_dev: ^1.4.0
  firebase_auth_platform_interface: ^6.2.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.5
  google_sign_in_platform_interface: ^2.1.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.5
  stack_trace: ^1.10.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/maps/
    - assets/.env
    - assets/icons/
    - assets/icons/consultancy/
    - assets/icons/tabs/
    - assets/icons/find_doctor/
    - assets/icons/feedback/
    - assets/icons/prevention/
    - assets/icons/prevention/doctors/
    - assets/icons/prevention/findings/
    - assets/icons/prevention/self_examination/
    - assets/intro_video.mp4
    - assets/badges/
    - assets/badges/body/
    - assets/badges/goggles-man/
    - assets/badges/goggles-woman/
    - assets/badges/armour-woman/
    - assets/badges/headband/
    - assets/badges/boots/
    - assets/badges/belt-man/
    - assets/badges/belt-woman/
    - assets/badges/cloak/
    - assets/badges/cloak-buckle/
    - assets/badges/gloves-man/
    - assets/badges/gloves-woman/
    - assets/badges/shield/
    - assets/badges/pauldrons/
    - assets/badges/achievement/
    - assets/badges/lines/
    - assets/badges_examination/
    - assets/badges_examination/custom_examination/
    - assets/badges_examination/dentist/
    - assets/badges_examination/colonoscopy/
    - assets/badges_examination/dermatologist/
    - assets/badges_examination/general_practitioner/
    - assets/badges_examination/gynecologist/
    - assets/badges_examination/mammogram/
    - assets/badges_examination/ophthalmologist/
    - assets/badges_examination/ultrasound_breast/
    - assets/badges_examination/urologist/
    - assets/sponsors/
