name: Continuous Integration v2
on: [ push, pull_request ]

env:
 flutter_version: '3.0.5'

jobs:
  format:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Flutter SDK cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
          cache-key: ${{ runner.OS }}-flutter-${{ env.flutter_version }}
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Copy .env.example into .env file
        run: sh ./bin/ci_workflow_scripts/env_copy.sh

      - name: Verify formatting dart
        run: sh ./bin/ci_workflow_scripts/verify_formatting.sh

  analyze:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Flutter SDK cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
          cache-key: ${{ runner.OS }}-flutter-${{ env.flutter_version }}
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Copy .env.example into .env file
        run: sh ./bin/ci_workflow_scripts/env_copy.sh

      - name: Analyze
        run: dart analyze
